### ISSUE TITLE
2.0.0.7 Alpha cant do benchmark test

### ISSUE THREAD

**Issue by blackoreo** [nicehash/NiceHashMiner2#102]
Iv installed new alpha version on my amd and 1080ti 6xrig
I cant perform benchamrk test at all i take 100%cpu and freezes

**Comment by jaretburkett** [comment]
Can you open the task manager and see what is specifically using up 100%?

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
