### ISSUE TITLE
2.0.0.7 - GPU mining not working

### ISSUE THREAD

**Issue by bmulvey1** [nicehash/NiceHashMiner2#103]
If I try to do any GPU mining while _**not**_ using a VPN (AWS East), any algorithms using the GPU get stuck in a loop of connecting and losing the connection. CPU mining (CryptoNight) always works, even when I'm not using a VPN. Logs and a screenshot of mining windows attached below.

[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1099245/log.txt)

![capture](https://user-images.githubusercontent.com/22732775/27503376-86343a6c-5849-11e7-93c7-a0d0b8ede826.PNG)

**Comment by bmulvey1** [comment]
Also doesn't seem to matter which service location I use

**Comment by eng1n88r** [comment]
Same issue here! Using 2.0.0.12.

**Comment by bmulvey1** [comment]
@exbarboss  Do you have an Asus router? Right now I'm thinking that it's a thing with Asus routers - I think it started after switching to a rt-ac3200, but I don't remember exactly when

**Comment by eng1n88r** [comment]
@mulveyben1 yes, I have AC-3200

UPD.

Found an issue
![capture](https://user-images.githubusercontent.com/883804/29597536-33278c76-8791-11e7-9b57-03b071b01e3b.PNG)
Should be switched off.

**Comment by bmulvey1** [comment]
@exbarboss yep, looks like it's working for me as well now
