### ISSUE TITLE
2.0.0.7 Doesn't detect GPU, manually using excavator works, though.

### ISSUE THREAD

**Issue by GiantTreeLP** [nicehash/NiceHashMiner2#104]
Since a few days ago NiceHash Miner doesn't detect my GPU (Nvidia GTX 980) anymore.  
`CudaDeviceDetection.exe` reports:

```
.\CudaDeviceDetection.exe
CUDA error in func 'CudaDetection::QueryDevices' at line 25 : all CUDA-capable devices are busy or unavailable.
```

Starting `excavator+web+restart_script.bat` manually (with a customized command file) works and mines without issues whatsoever.

Even closing nearly all applications doesn't get `CudaDeviceDetection.exe` to detect my GPU and if it does, then only for like 1 second before it is *busy* again.

**Comment by GiantTreeLP** [comment]
Okay, so I found the culprit:

`Optimize for Compute` somehow reserves the GPU in the driver, making it inaccessible to exclusive device locks.

Disabling that feature now allows the GPU to be detected again.

However: It worked with `Optimize for Compute` enabled, so I'm still leaving this open.

**Comment by Squall-Leonhart** [comment]
that setting is required for correct performance on maxwell v2 gpu's anyway.

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
