### ISSUE TITLE
Miner allows you to start if you have 0 devices

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner2#106]
If you have zero devices capable of mining, it will still allow you to start the miner and then it just hangs on Starting Miner

If both CPU and GPU are 0 it should provide an error and not let you click the Start button

![capture](https://user-images.githubusercontent.com/19168174/27518292-546dec1e-59aa-11e7-8b2b-7a3050bb0398.PNG)

**Comment by jaretburkett** [comment]
I've added this but to the 2.0.0.8 release todo. Thank you for pointing it out. Please leave it open, we will close it when fixed.

**Comment by S74nk0** [comment]
This is fixed with version v2.0.0.8 - v2.0.0.11.

Closing issue...
