### ISSUE TITLE
3rd party miner downloads

### ISSUE THREAD

**Issue by int3r** [nicehash/NiceHashMiner2#11]
I've been in the process of installing NHM2 on my nvidia rigs, and it has taken over 2 hours for the 3rd party miners to download (and still counting), despite being on a wired 120 mbps connection.

Not sure if that's a bug with the client, or is just coincidentally happening on multiple nvidia rigs (running Windows 7). 

I figured I'd report it just in case.

**Comment by S74nk0** [comment]
3rs party miners use the same download links as NHM1.
This is probably related to your connection.
