### ISSUE TITLE
the miner 2.0.0.7 shows CPU 0

### ISSUE THREAD

**Issue by a3177** [nicehash/NiceHashMiner2#110]
After updating to version 2.0.0.7 and restarting the computer, the m
![nice](https://user-images.githubusercontent.com/29724125/27573590-41dacea6-5b1b-11e7-8ed3-ab7d71026d04.jpg)
iner shows CPU 0

**Comment by billmcilhargey** [comment]
Noticed this too and I have an Intel i5 7th gen processor

**Comment by S74nk0** [comment]
This seems like a duplicate #95

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
