### ISSUE TITLE
Excavator 2.0.0.7 Issue

### ISSUE THREAD

**Issue by Cryptominer937** [nicehash/NiceHashMiner2#111]
If I minimize Excavator and NHM switches to another Algo like Eth randomly Excavator will not start mining again and does not get restarted by NHM.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
