### ISSUE TITLE
Starting NiceHash Miner forever on 2.0.0.7 win server 2008r2 enterprise

### ISSUE THREAD

**Issue by mahmoud1973** [nicehash/NiceHashMiner2#112]
Hello,
The program is stuck on this stage forever. I'm running 2.0.0.7 on windows server 2008 R2 enterprise sp1
64 Bit / Xeon E3-1240 v3 / 32 GB RAM 
all latest windows updates installed ...and .Net framework 3.5.1 installed.

The program just stays like this forever ..I left it for hours

See the screenshot 
https://prnt.sc/fpbxzk

and this is the log file ...
[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1110238/log.txt)

**Comment by S74nk0** [comment]
This is an issue with the CPU detection code and has been changed in nhm v2.0.0.8 and the upcoming v2.0.0.9. Even though this version of Windows isn't officially supported it should work with nhm v2.0.0.8 ([install vc_redist_2013 x86](https://github.com/nicehash/NiceHashMiner2/issues/137#issuecomment-319198098)).

Closing issue...

**Comment by angel12** [comment]
2.0.0.12 is having this issue on a 4cpu Xeon Windows Server 2016 fresh install.

**Comment by orphiler** [comment]
i too have a problem using nice hash and nice hash legacy :/ windows server 2016/2012 i tried on both
