### ISSUE TITLE
2.0.0.7 Alpha Only Mine on CPU with GPU Disabled Won't Work

### ISSUE THREAD

**Issue by moppidoo** [nicehash/NiceHashMiner2#116]
Under Devices having GPUs working but disabled (3x 1060 3GB) 1xi7 4770k
Nicehash will start Excavator-server and not launch XMR-STAK with only CPU enabled.

**Comment by S74nk0** [comment]
NiceHash Miner (v1 and v2) will disable the CPU by *default* in case there is/are GPUs present on the system. If you wish to use the CPU you will have to enable it manually. 

Closing issue...
