### ISSUE TITLE
Excavator Startup Parameters

### ISSUE THREAD

**Issue by Luke240** [nicehash/NiceHashMiner2#117]
Where's the best place to inject additional startup parameters to excavator? In the benchmark_GPU json file or in the bin for the individual miner?

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
