### ISSUE TITLE
Feature Request: 2.0.0.8 - When adding ClaymoreDual Miner 9.6 is now out

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner2#119]
https://github.com/nanopool/Claymore-Dual-Miner

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
