### ISSUE TITLE
CCminer.exe mssing. Problem reinstalling 

### ISSUE THREAD

**Issue by Rodisi** [nicehash/NiceHashMiner2#12]
Had a little problem with kaskerpsky with a false positive and deleted the bin directory in C:\Users\MYUSER\AppData\Local\Programs\nhm2 .
Program started normally, but when I tryed to start mining , it gave the error:
"windows can't find C:\Users\MYUSER\AppData\Local\Programs\nhm2\bin\ccminer_tpruvot\ccminer.exe"

Tried reinstalling , problem continues. But it continues mining.

**Comment by wewuzkingz** [comment]
I'm guessing Kaspersky is doing what my MalwareBytes did and is quarantining that miner.  You have to add an exception *and* restore the file from the quarantine location.

**Comment by Rodisi** [comment]
Yes, put the exclusion after , but it didn't work. Even stopped the antivirus completely and reinstalled nicehash 2, but still the same error. By the way even after uninstalling it ,getting rid of the folder AppData\Local\Programs\nhm2 and installing it again all the definitions are there. Are they kept in another folder or registry?

**Comment by wewuzkingz** [comment]
I had to add both users\me\appdata\local\programs\nhm2 and users\me\appdata\roaming\nhm2 to my exclusion list.

**Comment by Rodisi** [comment]
Ok , seems it worked , Thank you

**Comment by wewuzkingz** [comment]
Just glad my experience was able to help someone.  👍
