### ISSUE TITLE
NiceHashMiner2 - excavator_server HTTP API

### ISSUE THREAD

**Issue by Phuzzyhead** [nicehash/NiceHashMiner2#120]
How do I get the NiceHashMiner2 to start the excavator_server with the web-interface enabled?

**Comment by S74nk0** [comment]
@Phuzzyhead We will add an option for additional parameters so you can pass these yourself

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
