### ISSUE TITLE
NiceHash not benchmarking some of my nVidia cards

### ISSUE THREAD

**Issue by kalmargyula** [nicehash/NiceHashMiner2#121]
Hello,
I have a technical issue with one of my cards. I successfully used GTX 970 cards for mining, but recently I've added a GTX 980 ti into my rig. This card will not benchmark no-matter what i do ( remove the others, switch slots, reinstall drivers, update windows etc ). My gtx 970s work fine, but this GTX 980 ti refuses to work with the latest version of your software. 

LE. the same happened with some new gtx 1060 cards, benchmarking starts, then the program freezes and closes and that's all. Mining with the gtx 970 card still works without any issues!

Do you have any ideas or suggestions ? Anybody with a similar issue ?
Thank you a lot !

**Comment by billmcilhargey** [comment]
nvidia 1080s seem to have benched fine

i had 4 then added a fifth and it seems to have benched

**Comment by kalmargyula** [comment]
Hello, yep, all of these ( 980 and 1060 ) are benchmarking fine on a system belonging to a friend of mine, so there is clearly a small issue with my system. I am running win 10 64 bit. Anyone any ideas?

**Comment by kalmargyula** [comment]
Ok, found the solution. So for anyone having a similar issue try:

"run as administrator" when starting the program under windows ( mine was windows 10 pro ). This fixed the issue and all GPUs are benchmarked correctly now.

**Comment by S74nk0** [comment]
@kalmargyula When running as administrator do you have the same settings as when running as a non admin user? I don't see the connection with run as admin why it would fix it. Can you post the logs when running as admin and when running as a normal user?

**Comment by kalmargyula** [comment]
Hi, yes, exact same settings. If you tell me where can I find the logs, I'll post them :) But chances are that since benchmarking was completed, mining now would work but with simple 2xclick and with run as administrator option as well

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
