### ISSUE TITLE
Nvidia GTX 1080 Ti - No claymoredual mine option

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner2#123]
I thought in 2.0.0.8 ClaymoreDual Miner would be available as an option for the Nvidia cards?

Have nvidia GTX 1080 TI and dont see an option

![image](https://user-images.githubusercontent.com/19168174/27980869-513bd1f4-6351-11e7-8d41-fc688bf83517.png)
![image](https://user-images.githubusercontent.com/19168174/27980880-6a7fe394-6351-11e7-9005-b8dabe61a8e2.png)

As a side note, Is there a dual mining option?  Does excavator support this now?

**Comment by S74nk0** [comment]
We intend to replace all 3rd party miners gradually with excavator. Dual Mode will come through excavator.
There aren't any plans to support ClaymoreDual for NVIDIA.

Closing issue.
