### ISSUE TITLE
[v2.0.0.4 - FIXED] Benchmarking accuracy and settings

### ISSUE THREAD

**Issue by int3r** [nicehash/NiceHashMiner2#13]
On my nvidia rigs, sometimes it takes ~30 seconds before the cards actually start hashing/benchmarking, and thus the shorter benchmark times result in improperly calculated profitability. It would be nice to get the ability to change benchmark duration similar to the old client.

**Comment by S74nk0** [comment]
@int3r This will be fixed in the next release **v2.0.0.4**. We will close this issue after releasing **v2.0.0.4**.
![bench_choose](https://cloud.githubusercontent.com/assets/1517233/26449981/77f6eb6c-4155-11e7-9e57-7ceb63c4198a.PNG)

**Comment by S74nk0** [comment]
@int3r Expect a update notice in your NHM2 client or download the new version manually (keep link private please).

![update_example](https://cloud.githubusercontent.com/assets/1517233/26465676/5ffd44fc-418c-11e7-96f1-52e705b2dddd.PNG)

Closing...
