### ISSUE TITLE
2.0.0.8 System crash. Win 7 pro x64? 2xRX480 8Gb

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner2#131]
System crash. Win 7 pro x64? 2xRX480 8Gb
At the stage of the launch of the excavator server

Logs can not attach, because the application forgets to discard them to disk (or keeps the log file permanently open). After the reboot, I see only the logs of the load of the miners ...

**Comment by phr34k0** [comment]
Same. v2.0.0.8 Alpha is the same as the old. BSOD on random times. Useless update. Just remove excavator server already. Omg! >_>

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
