### ISSUE TITLE
2 0.0.8 Stuck on loading  (W10Pro x64)

### ISSUE THREAD

**Issue by gsoft** [nicehash/NiceHashMiner2#133]
After update 2 0.0.7->0.0.8 and run. NHM stuck with loader dialog....
https://1drv.ms/v/s!Amjuol8chaS4pVLEihcF70GQn46d

**Comment by nuieskater** [comment]
I has this problem too. 
I simply run program as windows 8 everything work fine. u may try.

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
