### ISSUE TITLE
Nicehash 2008 wont run on either GPU or CPU

### ISSUE THREAD

**Issue by Astrum7489** [nicehash/NiceHashMiner2#134]
Hey guys whats going on with Nicehash my NVidia rig wont mine starts with a 1sec screen then quits cant find out whats going on didn't have this problem on previous version, also doesn't work when I test on a different machine that's an i5 what gives Nicehash??

**Comment by Astrum7489** [comment]
Ok I seemed to have fixed this issue, I deactivated the start mining when idle option and its working again

**Comment by AlienUrineSampl** [comment]
How did you fix this? I'm having the issue of it 2.0.0.8 not detecting my card. only my cpu

**Comment by AlienUrineSampl** [comment]
Nevermind, figured it out. 

for future readers...

If you install a new GPU and drivers after NHM2 is already configured, it wont detect the gpu. reconfigure or all out uninstall and reinstall to configure new hardware.

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
