### ISSUE TITLE
Share above Target with new Excavator DaggerHashimoto

### ISSUE THREAD

**Issue by Phuzzyhead** [nicehash/NiceHashMiner2#135]
I'm getting periods where almost all shares are rejected as above target.
Running NHM2.0.0.8 with the excavator DagHash...
I have NEVER even once had a single share above target with any pervious miner and my cards run the same settings, so I definitely blame this one on the miner. I encountered a lonely stale share every once in a while and those seem to appear a little more frequently, too.
The most recent "above target period" was about 30 mins long. Stopping and restarting (miner button) got it back to accepting shares.

**Comment by S74nk0** [comment]
This issue is related to [excavator](https://github.com/nicehash/excavator). Please open an issue [here](https://github.com/nicehash/excavator/issues).

Closing issue...
