### ISSUE TITLE
Detects 8 GPUs but only runs 7

### ISSUE THREAD

**Issue by tiztrain** [nicehash/NiceHashMiner2#136]
So I have noticed when using NiceHash miner 2.0.0.8 that one GPU goes missing for some reason. It detects 8 GPUs in the home screen under available devices but when you start mining it only runs 7.

Thought I should log this one for you guys. Let me know if you would like more information.

**Comment by S74nk0** [comment]
@tiztrain If this was with one of the older NiceHash Miner v2 versions and the 8GPU was added afterwards it might be that the GPU is missing benchmarks. Please check if that is the case. Also please try using the latest v2.0.0.11 with this version new hardware should be bench-marked upon new starts.

**Comment by S74nk0** [comment]
Closing issue...
Related to an older version of NiceHash Miner v2
Please use the latest stable NiceHash Miner v2 version.
