### ISSUE TITLE
NiceHash 2.0.0.8 wont benchmark

### ISSUE THREAD

**Issue by D0ssis** [nicehash/NiceHashMiner2#138]
So I have GeForce 970 GTX 4gb and Intel i5-6600k, running Windows 10 Pro 64-bit.

The problem is that Nicehash wont do benchmark so I cant start mining. I have tried to disable antivirus software when installing and running Nicehash, no help, I have tried to run it as admin, no help.

No matter what I do, it just wont benchmark at all and let me mine.

Oh well, this is just an another reason to stay with MinerGate, their software atleast works.

**Comment by S74nk0** [comment]
@D0ssis Please try the latest NiceHash Miner v2.0.0.11. Most of the time users disable the devices or disable all algorithms (I don't know why). In the future please post the logs or use the bug reporter tool inside NiceHash Miner v2.

**Comment by S74nk0** [comment]
Closing issue... Related to an older version of NiceHash Miner v2
