### ISSUE TITLE
NiceHash 2.0.0.8 Download Stuck

### ISSUE THREAD

**Issue by LittleWickle** [nicehash/NiceHashMiner2#140]
I'm trying to download NicehHash Miner for my rig but then while downloading it, it gets stuck at downloading ccminer_cryptonight. It has been stuck for atleast about 30 mins now.

**Comment by S74nk0** [comment]
@LittleWickle Use the current latest v2.0.0.11 version. It has improved stability and we have removed support for ccminers.

Closing issue
