### ISSUE TITLE
Dagger hashimoto stop working

### ISSUE THREAD

**Issue by mustofasaifulkamal** [nicehash/NiceHashMiner2#141]
Dagger hashimoto can't always failed on standard benchmark, but if percise i get speed hash,. But after i run miner it disconect fluently and miner restart again,. And disconect again,.

**Comment by S74nk0** [comment]
@mustofasaifulkamal Use the latest version (v2.0.0.11) as one of the previous ones has a **bug** that would list **DaggerHashimoto** if your GPU has less than 3GB ram that is the reason it isn't working.

What NiceHash Miner version are you using and what is your GPU(s)?

**Comment by mustofasaifulkamal** [comment]
Okay so i have to download the latest version,. I use rx 550 4gb,. Thanks

**Comment by S74nk0** [comment]
@mustofasaifulkamal if the latest version is working correctly please close this issue. If there are still issues please state what miner is crashing or not working?

**Comment by mustofasaifulkamal** [comment]
Thank you, the latest version working correctly

**Comment by YevhenVe** [comment]
Hello, i have a 5 - NVIDIA 1060 3gb video cards and i using latest version 2.0.1.11 - NVIDIA. But i don`t see Dagger hashimoto in list. Why?
