### ISSUE TITLE
Cant start NiceHash miner

### ISSUE THREAD

**Issue by gianyadao** [nicehash/NiceHashMiner2#143]
![image](https://user-images.githubusercontent.com/30870832/29130048-e8c03c02-7d52-11e7-906f-3d07ee6d2895.png)

![image](https://user-images.githubusercontent.com/30870832/29130022-d59b5382-7d52-11e7-8c0d-b2c255c658c9.png)

**Comment by S74nk0** [comment]
@gianyadao what version is this?

**Comment by S74nk0** [comment]
@gianyadao this looks like v2.0.0.11. Please use 2.0.0.12.

**Comment by gianyadao** [comment]
2.0.0.11 

    On Thursday, August 10, 2017 9:31 PM, Stanko Krstić <notifications@github.com> wrote:
 

 @gianyadao this looks like v2.0.0.11. Please use 2.0.0.12.—

**Comment by gianyadao** [comment]
ohh okay i'll update it to 2.0.0.12 :D Thanks!  

    On Friday, August 11, 2017 4:14 PM, Gian Yadao <gianyadao_11@yahoo.com> wrote:
 

 2.0.0.11 

    On Thursday, August 10, 2017 9:31 PM, Stanko Krstić <notifications@github.com> wrote:
 

 @gianyadao this looks like v2.0.0.11. Please use 2.0.0.12.—
