### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by coinbutter** [nicehash/NiceHashMiner2#144]
I don't think this software should have a CAPTCHA. But since it does now, can you please increase the distance slightly between the letters to make it human readable?

**Comment by vanilla-thunder** [comment]
+1
It tooke me 3 tries, because some strange letter that looked like an "a" actually was something else 😆 
I have WQHD screen, so everything appears smaller than on a FHD screen

**Comment by S74nk0** [comment]
Our nhm-v1 was being bundled in many botnets so the CAPTCHA is something that would make it harder to bundle in... 

The CAPTCHA is just a one off entry and you will have an 8-digit input to solve. It is not user friendly I understand but it makes it a little harder to bundle in a botnet. And the users only encounter it **once** per machine.

Sorry for the inconvenience. 

Closing...

**Comment by hadees** [comment]
@S74nk0 I get why you added it but I'm running a rather large mining operation that uses PXE, the CAPTCHA basically makes it unusable for me.
