### ISSUE TITLE
NHM 2.0.0.11 doesn't star mining

### ISSUE THREAD

**Issue by eedut** [nicehash/NiceHashMiner2#146]
I mined about 2 days without problems but now when I start nhm it says my balance is 0 and when I start mining nothing really happends.
![desktop 08 12 2017 - 00 29 00 03](https://user-images.githubusercontent.com/29845232/29232883-ae9d3d90-7ef6-11e7-8f03-bcbb5288e291.png)
![desktop 08 12 2017 - 00 28 51 02](https://user-images.githubusercontent.com/29845232/29232885-aea26220-7ef6-11e7-9a22-dfc673c56cdc.png)

**Comment by Eks0n** [comment]
You need to download latest version 2.0.0.12 Happy mining :)

**Comment by eedut** [comment]
Oh... Thanks xd
