### ISSUE TITLE
All Time Crash with start as Admin

### ISSUE THREAD

**Issue by Knusperkeks2** [nicehash/NiceHashMiner2#154]
Hi,

If i start Nicehash Miner 2.0.0.12 without Admin rights Everything is okay.
But i start the Miner wirh this Admin right he Crash my computer and he reboot.

My System:
Windows 10 Pro 64 bit
4GB RAM
128 SSD
H110 Pro BTC
5x RX 480 8GB
3x Zotac 1060 with 6GB

Example:

Right click on the Dsktop Icon "Nicehash Miner 2" and start with administrator rights
after this Nicehash Miner 2 start and a console Windows opens (Excavator version 1.2.11a)
in this Windows check this program my GPUs with phymem?! i dont now
all my Radeon Card are ok and Correctly listed, but when he comes to the nvidia cards !CRASH!

Can you help me? :) or you need more Informations? And sorry my eglish ist very bad.. (from germany)

**Comment by S74nk0** [comment]
@Knusperkeks2 Please try the following. Open **%USERPROFILE%\AppData\Roaming\nhm2\configs** and edit **General.json** file after that start **nhm2** (when editing the config make sure nhm2 isn't running). Set the key to **ExcavatorIgnoreAMD: true**. Report back if this solves the crashes. Also mixed GPU rigs can degrade performance so it is best not to mix NVIDIA and AMD on the same system.

**Comment by S74nk0** [comment]
We have removed AMD support in NiceHash Miner2. 

Closing ...
