### ISSUE TITLE
[v2.0.0.4 - FIXED] Nicehash Miner V2.0.0.3 Alpha does not mine after benchmarks

### ISSUE THREAD

**Issue by Opc9** [nicehash/NiceHashMiner2#16]
The name of my PC is i7-975 after NHM V2 completes the benchmarking and when I click start miner
it says.

Windows cannot find 'C:\Users\i7'

Seems if there is a - sign in your windows username the miner will not work after the benchmarks run.

**Comment by S74nk0** [comment]
@Opc9 This will be fixed in the next release **v2.0.0.4**. We will close this issue after releasing **v2.0.0.4**

**Comment by S74nk0** [comment]
@Opc9 Expect a update notice in your NHM2 client or download the new version manually (keep link private please).

![update_example](https://cloud.githubusercontent.com/assets/1517233/26465676/5ffd44fc-418c-11e7-96f1-52e705b2dddd.PNG)

Closing...
