### ISSUE TITLE
Nicehash failing to benchmark daggerhashimoto/* with GTX1080 and then causes subsequent failures (2.0.1.2 beta)

### ISSUE THREAD

**Issue by TonyApuzzo** [nicehash/NiceHashMiner2#163]
So... after the last update there is a problem with the benchmarking causing the miner to crash and then go into a failed state.

It basically goes like this:

1. Launch NHM2
1. Start
1. Benchmark Runs
1. Benchmark crashes multiple times in a loop on all the daggerhashimoto/* algorithms
1. Eventually it fails back to the NHM2 GUI
1. NHM2 tells me "warning some benchmarks failed"
1. Meanwhile the daggerhashimoto benchmark keeps crash looping in the background
1. NHM2 tries to start mining with other algorithms but it does work
1. Hit Stop / Start / etc. and it won't kill the benchmarker keeps crashlooping
1. Exit / Restart
1. Same thing all over again
1. Manually turn off all the daggerhashimoto/* in the benchmark side
1. Works now (but of course not using those algorithms)

How do I get logs or troubleshooting info?  Poor experience.

**Comment by bjeff** [comment]
Same issue with gtx1070, error:

"CUDA error 'unknown error' in func 'cudahelp::get_device_name' line 26"

**Comment by arzon94** [comment]
Simliar issue with 1060 3gb

**Comment by 0mega47** [comment]
Same issue, dual gtx1080ti.

**Comment by freddanster** [comment]
Same issue, GTX1080 as well

**Comment by TonyApuzzo** [comment]
This is fixed for me in Beta 2.0.1.3.
