### ISSUE TITLE
Lyra2REv2 miner?

### ISSUE THREAD

**Issue by fonyo** [nicehash/NiceHashMiner2#178]
What miner is used to mine Lyra2REv2? Due to lack of neoscrypt support, I tried to replace NHM2 with MPM to mine on Nicehash, however the lyra2rev2 miners I tried with MPM are all failing after a while. Can you please disclose the miner included used for in NHM2?

**Comment by S74nk0** [comment]
NiceHash Miner 2 uses [excavator](https://github.com/nicehash/excavator) for NVIDIA GPU mining (all algorithms).

Closing issue.

**Comment by fonyo** [comment]
Cheers for the response
