### ISSUE TITLE
[v2.0.0.4 - FIXED] Memory leak(?) under Windows 10

### ISSUE THREAD

**Issue by bmulvey1** [nicehash/NiceHashMiner2#18]
Memory usage of the Miner 2 program goes up by ~1-2MB/s, both while mining and not mining. 
![desktop-05 24 2017-18 18 40 03](https://cloud.githubusercontent.com/assets/22732775/26428334/1700be10-40af-11e7-8557-132c4b19d920.gif)

**Comment by S74nk0** [comment]
@mulveyben1 This will be fixed in the next release v2.0.0.4. We will close this issue after releasing v2.0.0.4

**Comment by S74nk0** [comment]
@mulveyben1 Expect a update notice in your NHM2 client or download the new version manually (keep link private please).

![update_example](https://cloud.githubusercontent.com/assets/1517233/26465676/5ffd44fc-418c-11e7-96f1-52e705b2dddd.PNG)

Closing...
