### ISSUE TITLE
Not correctly optimizing profit for mixed Nvidia/AMD GPUs

### ISSUE THREAD

**Issue by wilstem** [nicehash/NiceHashMiner2#21]
GPU #1: GTX 1070
GPU #2: RX 480 8GB
GPU #3: RX 480 4GB

NiceHash Miner v2 chooses Equihash for all GPU's, however, when running previous NiceHash versions DaggerHashimx is much more profitable than Equihash for GPU #2,#3. Equihash tends to be most profitable for 1070 for both v2 and v1.7.5.7.

v2 continues to use Equihash for all GPU's even if restarted. DaggerHashimx was checked several times to be more profitable for the AMD GPU's during this time.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.6 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.6 Alpha**
