### ISSUE TITLE
Miner 2.0.0.3 SmartScreen and feedback!

### ISSUE THREAD

**Issue by cheddle** [nicehash/NiceHashMiner2#22]
FYI - Windows 10 Creators Update detects Nicehash 2.0.0.3 as unsigned and potentially dangerous. Apprecaite its Alpha bu you should sign your releases.

Feedback - the 'draw shape' "im a person" is great! - the GUI in general is very user friendly however I hope the advanced features of V1 are still present.

When benchmarking IDENTICAL GPU's you should provide the option to 'fast' bench and apply the same benchmark scores to the other GPU's as part of the general default user experience. I have been manually typing benchmark results into Nicehash for some time (copying the results from one precise run on a single GPU)

**Comment by cheddle** [comment]
Further - I think GUI should show what you are mining. I like to know.

**Comment by happyartifact** [comment]
The GUI does show mining details.  You just click on mining details.

**Comment by S74nk0** [comment]
@cheddle The Alphas are not likely to be always signed. The fast benchmark will be included with **Miner Group option** to group multiple Devices to one group and reference other devices in the group.
What is mining is shown in **Mining Details**. 

Will close this issue...
**Miner Group option** is in our internal TODO list.
