### ISSUE TITLE
NHM2 and Teamviewer

### ISSUE THREAD

**Issue by mrchence** [nicehash/NiceHashMiner2#24]
I use Teamviewer to remotely control my miners. In new version of NHM when i connect to my miner, i see white screen of NHM.

Also I use CPU without AES-NI support, but in NHM2 i see my CPU as available for mining.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
