### ISSUE TITLE
[v2.0.0.5 - FIXED] NiceHash Miner 2 runs multiple miner windows even after switching algorithms, interface also freezes over time

### ISSUE THREAD

**Issue by freedomtacos** [nicehash/NiceHashMiner2#26]
I think the best way to show it would be through a picture. 

![nhm2](https://cloud.githubusercontent.com/assets/11827609/26456809/380f23ca-413c-11e7-8096-10ebe9d971a3.png)

Basically on the old miner it used to close mining windows that weren't being used anymore after it switched algorithms, which you can see 3 instead of 2 for the cpu and gpu. 

Also a bigger issue is that the entire interface has frozen? on me multiple times. It's the white box on the screenshot and although it's frozen the miners are still running. But I just can't do anything like stop it without forcing it to shutdown.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**

**Comment by Fidelacho16** [comment]
It is still happening... it freezes everything...
