### ISSUE TITLE
[PLANED FOR - v2.0.0.7/8] Not seeing CPUs that 1.7 did

### ISSUE THREAD

**Issue by microtechies** [nicehash/NiceHashMiner2#27]
NiceHash 2 is not finding CPUs on some machines that I have

**Comment by wewuzkingz** [comment]
I had this happen with both CPUs and GPUs on both my machines.

At first my i5-4690k wasn't detected, and then it was.  Then my 980 wasn't, and then it was.  Then my R7 1700 and finally my 1080.  Re-launching NiceHash Miner *usually* fixed it.  For the 980 I had to change my nVidia driver from the one provided by Windows Update to the latest one from nVidia for it to get detected again.

**Comment by S74nk0** [comment]
We will check this. The Device detection modules will be updated for v2.0.0.7/8.

**Comment by S74nk0** [comment]
duplicate #95

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
