### ISSUE TITLE
[v2.0.0.5 - FIXED] 2.0.0.3 - Device Enabled/Disabled does not get remembered upon NHM2 restart

### ISSUE THREAD

**Issue by moppidoo** [nicehash/NiceHashMiner2#28]
I have a GTX760 that is inefficient at mining profit and disabled via GUI, however, once I restarted NHM2, it automatically enabled all devices, this is the only rig I have that also have CPU enabled, not sure if that had anything to do with it.

CPU i7-4770k
GPU1 - GTX760
GPU2 - GTX1060
GPU3 - GTX1060

**Comment by S74nk0** [comment]
@moppidoo This is fixed in v2.0.0.5. Expect the new release soon.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
