### ISSUE TITLE
[v2.0.0.5 - FIXED] Unable to benchmark Equihash OptiminerAMD

### ISSUE THREAD

**Issue by happyartifact** [nicehash/NiceHashMiner2#3]
Upon clicking benchmark, it tries and just reverts back to "Needs Benchmark" with N/A BTC/Day.  Older card:  AMD 7750.

**Comment by S74nk0** [comment]
@happyartifact this is probably due to the missing system variables. I believe this issue is [related](https://github.com/nicehash/NiceHashMiner2/issues/4). Please report back after 2.0.0.5 release.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
