### ISSUE TITLE
Stop mining when switch to DaggerHashimot on v2.0.0.3 alpha and v1 both

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner2#30]
Hi there!
Miner stops mining process when switch to DaggerHashimoto!!! It start to happens from yesterday when u release v2.0.0.3A.
I have this issue both on v2 and v1 nicehashminers.

![2017-05-25 6](https://cloud.githubusercontent.com/assets/28950108/26459616/b7ec2672-417f-11e7-9eb5-cda2e08539f6.png)

**Comment by arrmor** [comment]
So i really afraid to go sleep guys!!! I need help!

![2017-05-25 9](https://cloud.githubusercontent.com/assets/28950108/26460252/c058e9f6-4181-11e7-9264-53d15137bb2c.png)
![2017-05-25 10](https://cloud.githubusercontent.com/assets/28950108/26460251/c056dcb0-4181-11e7-8253-f4d56c763ef2.png)

**Comment by S74nk0** [comment]
@MrHump If this issue is present both on NHMv1 and NHMv2 it is most likely related to drivers. Can you provide the logs to be sure (both versions if possible). Post them here or email it to me at stanko@nicehash.com.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
