### ISSUE TITLE
[v2.0.0.4 - FIXED] Can not start mining (can't find some file)

### ISSUE THREAD

**Issue by DrCorvax** [nicehash/NiceHashMiner2#34]
After pressing START button I've got a message:

![image](https://cloud.githubusercontent.com/assets/8477436/26464456/88215942-4190-11e7-8ec1-d100145fc369.png)

ENG: "Can't find "C:\Users\Всеволод". Check file name and try again."
My user name is "Всеволод Грачев". The name is in russian and there is a space in name.

**Comment by arrmor** [comment]
майнер устанавливается по умолчанию в папку пользователя. Попробуй создать нового юзера с именем на англ языке и под ним установи майнер - все должно получиться.

**Comment by DrCorvax** [comment]
I've made 2 new users and test this issue:
1) User name "Сева" (russian, no spase) - all OK.
2) User name "user 2" (english, has space) - got the error message box.

I think the problem is in space symbol, not in russian letters.

BTW, all benchmarks are sucsessfully completed in every case.

**Comment by S74nk0** [comment]
Expect an update notice in your NHM2 client or download the new version manually (keep link private please).

![update_example](https://cloud.githubusercontent.com/assets/1517233/26465676/5ffd44fc-418c-11e7-96f1-52e705b2dddd.PNG)

Closing...
