### ISSUE TITLE
NiceHash Miner v2.0.0.4 NSIS Error installation issue

### ISSUE THREAD

**Issue by ChriscomIT** [nicehash/NiceHashMiner2#35]
Hi,

I've downloaded the v2.0.0.4 file and always get an NSIS Error from the installer file as u can see in the attached screenshot.

<img width="321" alt="nicehash 2 0 0 4 installer error" src="https://cloud.githubusercontent.com/assets/2799553/26469234/80ffc028-4199-11e7-9cf8-4f585f98ed01.PNG">

I've tried downloading it with several browsers, different PCs and checked antivirus as well. I also found out that 2.0.0.3 installer file is 37.6MB and the 2.0.0.4 installer file is just 23.1MB.

Anyone else has this problem?

Regards,

ChriscomIT

**Comment by ChriscomIT** [comment]
Ok, I fixed it myself with downloading the v2.0.0.4 installer file with my mobile phone and it worked out. Really weird.

**Comment by happyartifact** [comment]
Should 2.0.0.4 be available for download?  I'm not seeing any releases for NHM 2 at all at this time.

**Comment by ChriscomIT** [comment]
@happyartifact Yeah if u go on the NiceHash miner alpha download page and just hit the download button u should get the download v2.0.0.4 alpha. There is no update message or something like that. U have to regularly check the download page. Also, support confirmed the version but they do not see the installer/download error I have.

**Comment by ChriscomIT** [comment]
@happyartifact  Sorry I was wrong. I learned that there is indeed an update notification directly in the app as u can see here: https://github.com/nicehash/NiceHashMiner2/issues/13

**Comment by DrCorvax** [comment]
I've got same problem. The size of installation file is 23.1 MB and there is an Integrity check error. And I don't have any link to new version in my miner v. 2.0.0.3.

**Comment by ChriscomIT** [comment]
@DrCorvax Try to download it via mobile phone if possible and transfer it to ur PC via USB cable. It worked out for me.

**Comment by allfa** [comment]
looks like depending on the location its downloading with diferent size.
in my country i got 11.6mb using a proxy i got 9.6 and using a us proxy got the right one 37.6

**Comment by ChriscomIT** [comment]
With v2.0.0.5 this issue isn't present for me anymore and everything downloaded and installed fine so this issue can be closed I think.

**Comment by S74nk0** [comment]
@ChriscomIT There is still a rare possibility for this to happen. We will close it after the next release

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
