### ISSUE TITLE
[v2.0.0.5 - FIXED] double-clicking start opens two miner windows and clicking stop only closes one

### ISSUE THREAD

**Issue by cheddle** [nicehash/NiceHashMiner2#36]
as above. double clicking start creates an unkillable miner until closing nicehash miner v2 and reopening

**Comment by cheddle** [comment]
version 2.0.0.3

**Comment by ChriscomIT** [comment]
Just open the config file (general.json) and edit the "AllowMultipleInstances" to false.

**Comment by S74nk0** [comment]
@cheddle This issue should be fixed in v2.0.0.5. We will be releasing it soon.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
