### ISSUE TITLE
"update available" - NSIS Error

### ISSUE THREAD

**Issue by cheddle** [nicehash/NiceHashMiner2#39]
---------------------------
NSIS Error
---------------------------
Installer integrity check has failed. Common causes include
incomplete download and damaged media. Contact the
installer's author to obtain a new copy.

More information at:
http://nsis.sf.net/NSIS_Error
---------------------------
OK   
---------------------------

^^

Error given when clicking update - has happened twice now.  on 2.0.0.3 and trying to grab 2.0.0.4

**Comment by ChriscomIT** [comment]
Hi, this was already reported here https://github.com/nicehash/NiceHashMiner2/issues/35 . Also there I provided a solution.

**Comment by S74nk0** [comment]
Closing [duplicate](https://github.com/nicehash/NiceHashMiner2/issues/35)
