### ISSUE TITLE
[v2.0.0.5 - FIXED] Nice Hash Miner 2.0  Questions 

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner2#4]
Hello , fist of all thanks for sending me the link ... i have a question in the new miner 2.0 ... to add in the claymore dual , dual mining i have to edit the config files for each gpu and put this ??

{
"Name": "ClaymoreAMD_Equihash",
"NiceHashID": 24,
"MinerBaseType": 4,
"MinerName": "equihash",
"BenchmarkSpeed": 0,
"ExtraLaunchParameters": "-dual=Pascal", ?????
"Enabled": true,
"AlgorithmStringID": "ClaymoreAMD_Equihash",
"MinerBinaryHashID": ""

2nd question where are the Miner System variables , are they addded already or u still going to add them later on ???

in the old one u had a MinerSystemVariables.json with this 👍

bin\sgminer-5-6-0-general\sgminer.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "1"
},
"bin\sgminer-gm\sgminer.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "1"
},
"bin_3rdparty\claymore_cryptonight\NsGpuCNMiner.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "1"
},
"bin_3rdparty\claymore_zcash\ZecMiner64.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "1"
},
"bin_3rdparty\optiminer_zcash_win\Optiminer.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "1"
},
"bin_3rdparty\claymore_dual\EthDcrMiner64.exe": {
"GPU_MAX_ALLOC_PERCENT": "100",
"GPU_USE_SYNC_OBJECTS": "1",
"GPU_SINGLE_ALLOC_PERCENT": "100",
"GPU_MAX_HEAP_SIZE": "100",
"GPU_FORCE_64BIT_PTR": "0"
}
}

**Comment by S74nk0** [comment]
@MACE-Zer0 This feature will be in the next Alpha release (2.0.0.5).

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
