### ISSUE TITLE
[v2.0.0.5 - FIXED] Daily estimated earnings do not count

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner2#43]
After few hours of running 2.0.0.4 Daily estimated earnings counter don't work, but mining process going well.

![2017-05-26](https://cloud.githubusercontent.com/assets/28950108/26489181/04254e94-420f-11e7-92f3-564d02b7c3a4.png)

**Comment by arrmor** [comment]
And as u see in excavator mining window i have only 5 videocards, so he do not see my 6th GPU, but nicehash miner detect all 6... V 1.7.5.12 work fine with all 6 GPU...

**Comment by S74nk0** [comment]
@MrHump Please post the logs.

**Comment by arrmor** [comment]
where do we have log file? can't find it on default directory.

**Comment by arrmor** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1032009/log.txt)
Here it is) so in the very end u can see that ETH miner detects only 0-4 GPU but i have 6 of them!
When i switch to v1 nicehashminer it detects all 6 gpu and works fine for me now (even not trying to mine ETH on gtx 1070))
TY for replying and help!

**Comment by janeseo** [comment]
Same for me too

**Comment by S74nk0** [comment]
@MrHump @janeseo This issue is fixed in v2.0.0.5. We will be releasing it soon.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
