### ISSUE TITLE
New block detected

### ISSUE THREAD

**Issue by aofxta** [nicehash/NiceHashMiner2#44]
![untitled](https://cloud.githubusercontent.com/assets/10006208/26489400/6cb9f76c-4231-11e7-8ab3-856e35ef0bca.jpg)

**How Do I fix this issue?**

**Comment by ChriscomIT** [comment]
This is no issue and there is no fix for it. It's simply just the normal behavior and indicates that a new block was detected (on the server) which will be worked on (your client side).

**Comment by S74nk0** [comment]
@aofxta This is expected behavior... 
Closing
