### ISSUE TITLE
[v2.0.0.5 - FIXED] V2 seems less profitable

### ISSUE THREAD

**Issue by andyrew66** [nicehash/NiceHashMiner2#45]
My benchmarks are significantly lower on v2 then v1 only wants To mine cryptonight where as v1 will mine purely eth.

Will duel mining be reintroduced

**Comment by arrmor** [comment]
Yeah, I've got some problems with this too) I have 6 x 1070's and v1 mine almost 90% Equihash, but now on v2 miner go with shit ton of other algo((

**Comment by S74nk0** [comment]
@andyrew66 @MrHump Please post the logs.

**Comment by janeseo** [comment]
Do we paste the logs here or do we email to you

**Comment by S74nk0** [comment]
@janeseo You can post it here or email it to me (stanko@nicehash.com)

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
