### ISSUE TITLE
[v2.0.0.5 - FIXED] Application not Synchronizing with Miners

### ISSUE THREAD

**Issue by MinecraftAddict131** [nicehash/NiceHashMiner2#46]
![](http://i.imgur.com/bYj2kVV.png)

**Comment by TrojanLeHorse** [comment]
I too encountered an issue that parallels this one, however it was also accompanied by another issue, which was far worse and actually effected my performance.

**Comment by S74nk0** [comment]
@MinecraftAddict131 This points to a known issue fixed in v2.0.0.5. We will be releasing it soon.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
