### ISSUE TITLE
[v2.0.0.5 - FIXED] Application initiating endless loop of CUDA Memory Errors

### ISSUE THREAD

**Issue by TrojanLeHorse** [nicehash/NiceHashMiner2#47]
I'm unable to show the exact issue at this moment, as I intend to mine for the majority of the day, and thus have already swapped back to NiceHash Miner V1, as I have never encountered any errors on it. However, the issue was, I had literally just installed and opened NiceHash Miner V2, and upon allowing it to mine for a while, while I was AFK, I returned to see that the daily earnings weren't working, and additionally numerous CMD iterations were rapidly popping up, all showing a Nvidia GPU related memory error before abruptly creating another iteration and repeating. IDK what this was, but it was essentially going to result in my PC crashing, as I could already see explorer.exe constantly crashing and refreshing (as indicated by a flashing background, that flashes to the theme I set for windows and back to the actual wallpaper I set, and the task bar and start icons disappearing and coming back. I've never encountered any errors of this sort, ever.

**Comment by TrojanLeHorse** [comment]
Would happily show a log file, if it recorded these events, however I have no idea where to locate it. Any ideas? Or is it just in the directory that it was installed in?

**Comment by S74nk0** [comment]
@TrojanLeHorse The described issues are pointing to a couple of known BUGs that are fixed in v2.0.0.5 - Alpha. We will be making this release public soon. Log files are under **%USERPROFILE%\AppData\Roaming\nhm2\logs**. You can post them here or send them to **stanko@nicehash.com**

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
