### ISSUE TITLE
[v2.0.0.5 - FIXED] GUI losing control over miners

### ISSUE THREAD

**Issue by Yoshi-E** [nicehash/NiceHashMiner2#48]
Once you start the miners they are not controlled by the Application anymore and can no longer be stoppend over the interface.
Closing the Miners will just restart them.
Algorithms are not changing.
![image](https://cloud.githubusercontent.com/assets/11833269/26575173/61bcb804-4524-11e7-838b-8fa678ea8c5a.png)

**Comment by S74nk0** [comment]
@Yoshi-EE This shouldn't be an issue anymore in v2.0.0.5 next Alpha release. Also this shouldn't be an issue in v2.0.0.4 Alpha I see you are using v2.0.0.3.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
