### ISSUE TITLE
Multiple NVidia miners running

### ISSUE THREAD

**Issue by coinbutter** [nicehash/NiceHashMiner2#49]
Running NHM2.0.0.4 over the weekend, found 7(?) NVidia miners running upon unlocking computer. The processes were being monitored by NHM2 as when I closed the windows they were automatically restarted even when NHM2 was told to stop mining. Once NHM2 was closed all the miners could be shut off.

GTX 750Ti. No CPU miner running that was controlled by NHM2. Windows 10 Pro x64.

**Comment by CreamyG31337** [comment]
I tried a few days ago in an earlier version and it did this almost instantly. Didn't file a bug because it's so obvious but now I tried the new version and it blows my mind that it still does this. Completely unusable. How are we supposed to beta test it when it's got bugs like this that make it useless?

**Comment by coinbutter** [comment]
I'll try NHM2 again, once a newer version is released.

**Comment by ChriscomIT** [comment]
Yeah hopefully, this will be finally resolved in v2.0.0.6 as with this issue it's very annoying to use/or test the v2 miner for a longer time or without checking it regularly and closing the window manually. Also, it decreases the payout flow until u closing the wrong cmd window manually (not much but its noticeable).

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.6 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.6 Alpha**
