### ISSUE TITLE
CPU doesn't benchmark with GPU's

### ISSUE THREAD

**Issue by JladanZA** [nicehash/NiceHashMiner2#5]
Not so much an issue as an annoyance. Had to go and find the CPU setting and benchmark it separately before I could mine with it. Might be by design as most people use GPU's?

**Comment by int3r** [comment]
Same issue, and, as a related problem, because the CPU doesn't benchmark with the GPU, CPU mining will not start, even when it is selected in the client.

**Comment by S74nk0** [comment]
If there are GPUs detected CPU will be disabled only on the first run. One can enable CPU in the settings.
Closing issue...
