### ISSUE TITLE
Nvidia 780ti

### ISSUE THREAD

**Issue by meepominer** [nicehash/NiceHashMiner2#51]
Nicehashminer starts up excavator automatically and it seems it does not support nvidia gtx 780 ti, so the window of excavator keeps opening and closing indefinitely.

**Comment by ChriscomIT** [comment]
I don't think this is related to your graphics card. It seems to be a bug, especially with the new v2.0.0.5.

Take a look at the issue: #49 and the issue I referenced there.

**Comment by meepominer** [comment]
excavator outputs:

AppData\Roaming\nhm2\bin\excavator_server>excavator -p 4000

==================== www.nicehash.com ====================
         Excavator v1.2.4a GPU Miner for NiceHash.
    Copyright (C) 2017 NiceHash. All rights reserved.
Developed by djeZo and zawawa with help and contributors:
    pallas, Vorksholk, bitbandi, ocminer
==================== www.nicehash.com ====================

Build time: 2017-05-30 12:06:07
Build number: 18
Provided startup commandline:
        excavator  -p 4000

[15:36:49][0x000032c8][info] Log started
[15:36:50][0x000032c8][error] core | No compatible devices found!

and I have other nvidia cards (more modern) that seems to work fine.

Also previous versions of nicehash miner 2 did not open this excavator server window...

**Comment by ChriscomIT** [comment]
Yeah, that's correct because this issue appeared with 2.0.0.5 and should be fixed. From the output of the excavator cmd it actually really seems your graphics card isn't supported which should not be correct IMO. GTX 780Ti is capable I think but the miner needs an update as it seems.

**Comment by S74nk0** [comment]
**GeForce GTX 780 Ti** is **SM 3.5**. **excavator** only supports NVIDIA GPUs with **SM 5.0+**. Older GPUs are not planned to be supported officially.
Closing issue...

**Comment by ChriscomIT** [comment]
@S74nk0 Thanks for the clarification. Was not sure about the SM version that v2 will finally support.
