### ISSUE TITLE
Start Mining when idle ignores already running Miners

### ISSUE THREAD

**Issue by Yoshi-E** [nicehash/NiceHashMiner2#55]
Nicehash 2.0.0.5 - Alpha RAD
OS: Windows 10 x64
Mining GPU and CPU
"Start Mining when idle" : activated
After manually starting the miner, everything works as intended, but after some time (idle) the miner is starting a second set of miners.
After moving the mouse, the second set of miners closed, but the first set of miners can no longer be stopped as Nicehash does not show the option for it.

**Comment by coinbutter** [comment]
I think this is the same/similar issue as #49.

**Comment by ChriscomIT** [comment]
Yeah, basically it is the same issue. I don't know why people don't check already reported bugs and report them multiple times. Github is an advanced platform. I don't get why people don't use these advanced features and open issues  3 or 4 times which already were reported. 

That makes it very much harder for the developer!
