### ISSUE TITLE
[NHM2 2.0.0.5 - Alpha RAD] Minor GUI error in Hardware Details

### ISSUE THREAD

**Issue by theLosers106** [nicehash/NiceHashMiner2#56]
![image](https://cloud.githubusercontent.com/assets/15833762/26674643/acc23498-46f3-11e7-9d49-cc3a4ed08578.png)

As you can see for the CPU there is a dropdown icon (highlighted in red) while the GPU is missing that same icon. Both can expand and retract properly.

**Comment by ChriscomIT** [comment]
Same here for me. But the dropdown does not expand for me. It's just the icon for me which do nothing.

Maybe it's a for a suggestion I made. To be able to change CPU cores/threads manually and on the fly. Maybe that will be handled with the dropdown icon but the functionality behind is not yet implemented. But that's just a random guess.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
