### ISSUE TITLE
Nicehash miner 2.0.0.5 Failed to load phymem.sys

### ISSUE THREAD

**Issue by wtc2** [nicehash/NiceHashMiner2#57]
Miner 2.0.0.5 issue: Failed to load phymem.sys - A digitally signed driver is required. Windows blocked the installation of a digitally unsigned driver.
Wont run GTX970's or sometimes 2 of the 3.
System is Windows 10, 3-GTX970s, 2-RX470s.
GTX970 driver latest version 22.21.13.8233.
All run fine on 1.7.5.12.
Any help is appreciated and great product/partnership.

[13:54:21][0x000010a0][info] Log started
[13:54:22][0x000010a0][error] opencl | Failed to load phymem.
[13:54:22][0x000010a0][info] core | Found CUDA device: GeForce GTX 970
[13:54:22][0x000010a0][info] core | Found CUDA device: GeForce GTX 970
[13:54:22][0x000010a0][info] core | Found CUDA device: GeForce GTX 970
[13:54:22][0x000010a0][info] core | Found OpenCL device: "AMD Radeon RX 470"
[13:54:22][0x000010a0][info] core | Found OpenCL device: "AMD Radeon RX 470"
[13:54:22][0x000010a0][info] api | Listening on 127.0.0.1:4000
[13:54:22][0x000010a0][info] core | Initialized!

**Comment by S74nk0** [comment]
@wtc2 Run NHM2 as Administrator, **phymem** will be loaded then.
Reopen this issue if **Run As Administrator** doesn't work

**Comment by S74nk0** [comment]
@wtc2 The **phymem.sys** driver is only needed for AMD GPUs  for certain algorithm to work at full speed. When running with NVIDIA GPUs you don't need to worry about this. 

Closing...

**Comment by alkesh1980** [comment]
I just got this on 2.0.0.7.
<img width="1051" alt="screen shot 2017-06-15 at 6 04 40 pm" src="https://user-images.githubusercontent.com/22535930/27203745-4e7a1272-51f5-11e7-9502-828881c79f97.png">

**Comment by S74nk0** [comment]
@alkesh1980 after we get the certs for the driver (phymem.sys) this will not be an issue anymore. You can ignore this for now. Keep in mind excavator is still in Alpha.

**Comment by alkesh1980** [comment]
Understood, just helping report bugs.


Thanks!

**Comment by S74nk0** [comment]
@alkesh1980 No problem. Please report 👍

**Comment by IanJNB** [comment]
Mine says that I should run NiceHash 2 as an Administrator which is not a problem except that I need to put nicehash.exe into Startup so that it automatically restarts after a power failure. 
I ticked the admin box in the shortcut but it won't run out of Startup. 
Any suggestions please?

**Comment by S74nk0** [comment]
@IanJNB If you aren't running AMD GPUs please ignore the message.

**Comment by IanJNB** [comment]
S7nk0 - I am running AMD RX580 cards...

**Comment by IanJNB** [comment]
Are you saying that I should just ignore the message?

**Comment by S74nk0** [comment]
@IanJNB In this case run NiceHash Miner 2 as Admin to get the full speed of excavators **DaggerHashimoto** and **Equihash**. This is only needed when running excavator with AMD GPUs and only for the 2 aforementioned algorithms.

**Comment by Itdoesntworkright** [comment]
I have the same 2 problems... But how to run as Admin and the fail to load Phymem. Any tutorials/vidz on how to actually doing it? Thanks in advance!
