### ISSUE TITLE
2.0.0.5  Shows Daily Estimated Earnings at 0. 

### ISSUE THREAD

**Issue by Worldchamp** [nicehash/NiceHashMiner2#58]
Never changes even while mining.

Windows 10 x64 Latest build
I7-4770k
GTX 1080

**Comment by ChriscomIT** [comment]
Can you please be more detailed? Is it for CPU or GPU? There were fixes for this in 2.0.0.5 and only CPU (xmr miner) causes some actually problems with DEE for me as it sometimes randomly doesn't show up.

Please be more specific and detailed in future reports! Thanks!

You can also check out issue #40 .

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
