### ISSUE TITLE
Income was not credited

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner2#59]
Hey there!

06/03/2007 as you can see on screenshot it was a pause on mining from 01:45 till 2:00.
![2017-06-03](https://cloud.githubusercontent.com/assets/28950108/26751419/c4b7f034-4841-11e7-8762-fd007a9140d4.png)
But logs are telling different story: 
[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1049429/log.txt)
How can it be possible? There were no rejected shares etc.

TY for help and have a Nice day)

**Comment by ChriscomIT** [comment]
Is it the same on the old website? The new website is not fully ready yet and sometimes stats are down for maintenance. Check if the old website shows same and report back. Thanks!

**Comment by S74nk0** [comment]
Not related to NiceHash Miner v2. Check old website or write to support@nicehash.com
Closing...
