### ISSUE TITLE
Nice HashMiner 2.0 CryptoNight (XxnrStackCPU) BenchMark not working

### ISSUE THREAD

**Issue by Hannibaldz** [nicehash/NiceHashMiner2#6]
when BenchMark CryptoNight (XmrStackCPU) will stay Needs Benchmark and not Start mining cpu

**Comment by Faux-Grey** [comment]
I had a similar issue, have you whitelisted the mining exe with your antivirus?
I found my antivirus was deleting it whenever I attempted to run it Benchmark/Mining.

**Comment by S74nk0** [comment]
@Hannibaldz please post the logs folder (zipped) here or send it to stanko@nicehash.com. The issue could be related to what @Faux-Grey is describing.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
