### ISSUE TITLE
Miner tries to use 1 gpu to mine 2 coins.

### ISSUE THREAD

**Issue by meepominer** [nicehash/NiceHashMiner2#60]
Nicehash Miner fails to close the previous miner algorithm when it starts to mine a new coin with the gpu, resulting in two mining windows open for the same gpu and reducing the average profitability.
Ex: when mining equihash with excavator, it opens a ccminer window and starts mining Myriad-Groestl.

I have to disable manually all algorithms except the one I want to keep on mining with the gpu to avoid this issue.

**Comment by ChriscomIT** [comment]
Hi, this was already reported here #49 and here #50 . Please check already opened issues before creating new ones twice! Thanks!

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.6 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.6 Alpha**
