### ISSUE TITLE
[v2.0.0.8 - FIXED] Dual Mining with ETH

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner2#61]
So I was thinking on how this could be implemented directly from the NHM2.

As I know, NHM2 passes command-line options to miners, right?

So it shouldn't be so difficult to implement this.

During benchmark it should just test all the combinations and sum up profitability from both algos (ex. ETH+DCR)

And then just choose the most profitable combination for actual mining.

**Comment by giosal** [comment]
plus, as I can see it was already implemented in 1.7.5.13, so shouldn't be that difficult

**Comment by S74nk0** [comment]
@giosal this will be in the next version v2.0.0.8. Will close this issue after v2.0.0.8 release

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
