### ISSUE TITLE
Nicehash 2.0.0.5 miner not benchmarking all algo's

### ISSUE THREAD

**Issue by alkesh1980** [nicehash/NiceHashMiner2#62]
I am running GTX 1080's and I am only able to benchmark equihash, pascal, decred, and sia. All others just say Need Benchmark. I already deleted the old benchmark files and tried to do a fresh benchmark, but it does the same thing.  It is only mining Sia so far, which may be the best algo, but I am not sure.  Am I missing something?

**Comment by S74nk0** [comment]
@alkesh1980 what was the issue? Why did you close this?

**Comment by alkesh1980** [comment]
Nobody was replying so I decided to email support about it.  

The issues is ccminer is disabled on my machine when I look at the logs on version 2.0.0.5 and 2.0.0.0.6.
