### ISSUE TITLE
A Javascript error has occurred in the main process

### ISSUE THREAD

**Issue by alkesh1980** [nicehash/NiceHashMiner2#64]
I get this when I launch 2.0.0.5

A Javascript error has occurred in the main process
Uncaught Exception
Error: EPROM: Operation not permitted, open
'C:\Users\admin\AppData\Roaming\nhm2\tmp_bins\ccminer_cryptonight.zip'

I get that for other files in the same directory.  
![capture](https://user-images.githubusercontent.com/22535930/26934893-93c2dea8-4c38-11e7-9f64-d908db5c65e4.PNG)

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**
