### ISSUE TITLE
2.0.0.6 Not showing daily profits

### ISSUE THREAD

**Issue by Crypto-Lord** [nicehash/NiceHashMiner2#66]
Ver. 2.0.0.6 isn't showing the daily profits within the program. Mining window shows progress and website shows the miner is working. Also the mining details show the daily profit 
![2](https://user-images.githubusercontent.com/28488696/26956158-b8fca676-4c89-11e7-929a-7bba9f3e1ea6.png)
![untitled](https://user-images.githubusercontent.com/28488696/26956157-b8fb418c-4c89-11e7-9783-71eeb202695f.png)

**Comment by Crypto-Lord** [comment]
Appears to be working now

**Comment by S74nk0** [comment]
@Crypto-Lord ethminer/Dagger has a little delay when generating DAG. That is probably the issue here

**Comment by Crypto-Lord** [comment]
it was taking pretty long usually over 10-20 minutes, but eventually started showing profits. Was just odd that the previous version was instant for showing profits.

**Comment by S74nk0** [comment]
@Crypto-Lord  v2.0.0.6 had a critical issue with almost all miners. This is fixed with v2.0.0.7
