### ISSUE TITLE
[v2.0.0.5 - FIXED] No SIA algo?

### ISSUE THREAD

**Issue by happyartifact** [nicehash/NiceHashMiner2#7]
Why isn't SIA algo included in this?  It's just the newest version of Excavator, right?

**Comment by S74nk0** [comment]
@happyartifact **SIA** will land in NHM v2.0.0.5 on **26th of may 2017**.

**Comment by janeseo** [comment]
Today is already the 27th of May, When will it get released

**Comment by ChriscomIT** [comment]
@S74nk0 @janeseo Yeah I had the same thought/question. Sadly waiting the whole time and v2.0.0.4 is very unstable and have a lot of bugs. Hopefully, it will be released this weekend and not be delayed until next week.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**
