### ISSUE TITLE
v2.0.0.6 GUI doesn't seem to properly be monitoring algorithms

### ISSUE THREAD

**Issue by larathydo** [nicehash/NiceHashMiner2#74]
Hello,

I've been trying to use v2.6.0.6 and I've noticed that the GUI seems to be unaware of the algorithms' status / progress when the 'start' button is pressed. For example, immediately after hitting start, for a brief second you see the following screenshot (with the yellow/gold 'running' animation):

![2606_startup](https://user-images.githubusercontent.com/17834282/27015809-34490ff2-4eee-11e7-81d1-477b5ba375fd.jpg)

But almost immediately after, it goes back to a state as though it's indicating that nothing is running:

![2606_running](https://user-images.githubusercontent.com/17834282/27015815-59118652-4eee-11e7-84f0-1ac87f610851.jpg)

While I can see the algorithm running in a separate window all the white I see no 'Daily Estimated Earnings' updates, and it just constantly says "Ready for mining! Start Now!" at the bottom. It's as though the main GUI window is not communicating properly with the running algorithms?

Anyone else encounter this or know how to fix it?

Also, assuming I can get the above working properly... with the prior v1.7.5.12 version I was using there was an option to hide/minimise the algorithm window. Is there such an option in v2.0.x?

**Comment by larathydo** [comment]
If it's helpful my system specs are below

Windows 10 x64
Intel Core i5 4690k
16GB Ram
AMD Radeon RX 480

UAC is disabled, I've manually assigned full control security rights to my user account on the following paths, assigned recursively. They seem to be the working directories that NHM2 use:

C:\Users\<MyUserName>\AppData\Roaming\nhm2
C:\Users\<MyUserName>\AppData\Local\Programs\nhm2

**Comment by larathydo** [comment]
Finally, if it's useful here's a copy of the log.txt file from opening NHM2 until directly after clicking start (where nothing happens).

[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1066869/log.txt)

**Comment by Squall-Leonhart** [comment]
disabling uac is something that people who WANT issues do.

**Comment by larathydo** [comment]
It was a test, enabling / disabling UAC doesn't seem to impact the issue. 

I've seen UAC redirect program files (configs, etc) to the Virtualstore directory before, so I figured it was worth a shot trying to see if it was a behavior related to UAC.

**Comment by larathydo** [comment]
I just uninstalled NHM2 v2.0.0.6 and acquired v2.0.0.5 and it seems to be working correctly for me.  This seems to be an issue which only happens for me in v2.0.0.6.

Just need to figure out how to switch the algorithms from using EU region servers to the NA / US region now.

**Comment by S74nk0** [comment]
@larathydo the described issue is [same/related](https://github.com/nicehash/NiceHashMiner2/issues/73). Closing duplicate...
