### ISSUE TITLE
2.0.0.6 cant start benchmark if select all algo

### ISSUE THREAD

**Issue by pnpwin** [nicehash/NiceHashMiner2#75]
2.0.0.6 cant start benchmark if select all algo:
```
{"name":"NHM","hostname":"pnpwin-desktop","pid":6420,"level":30,"msg":"[MINING] C:\\Users\\pnpwi\\AppData\\Roaming\\nhm2\\bin\\excavator_server\\","time":"2017-06-12T18:57:08.347Z","v":0}
{"name":"NHM","hostname":"pnpwin-desktop","pid":6420,"level":30,"msg":"[ExcavatorServer] child process exited with code null","time":"2017-06-12T18:57:11.479Z","v":0}
```
but single benchmark cat run.
And if i uncheck excavator in bench and start all benchmark, i have same issue.

**Comment by S74nk0** [comment]
@pnpwin Please upload the whole logs folder. Benchmark All will only benchmark enabled algorithms of enabled devices.
Reopen issue if the issue is still present after enabling devices and algorithms.

**Comment by pnpwin** [comment]
logs attached @S74nk0 
[logs.zip](https://github.com/nicehash/NiceHashMiner2/files/1078688/logs.zip)
