### ISSUE TITLE
Ver .6 

### ISSUE THREAD

**Issue by yearight** [nicehash/NiceHashMiner2#76]
EthDcrMiner64 throws an error...(server: bind failed with error: 10048...remote management port is busy). It appears to accept a share and do a few hashes(in blue)?? then throws the error and repeats. No profit is shown in the app for my gpus.
Mining details section shows the CPU hashing, but not the gpus. Daily estimated earnings are 0.
Online stats shows cpu earning, but gpus not very much.

AMD 8120 8 core CPU
2 x R9 380s
Win 10
8 gigs Ram

[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1070009/log.txt)

**Comment by S74nk0** [comment]
This issue is same as #73. It is fixed and it will be available in the next release. I will close this as it is a duplicate.
