### ISSUE TITLE
GTX 970 slows down to 40sols/s

### ISSUE THREAD

**Issue by DrRobotto** [nicehash/NiceHashMiner2#77]
With the new nicehash miner 2.0.0.6 my GTX 970 slows down from around 250 sols/s to about 40sols/s after some hours of operation. This error does not occur on the old nicehash miner 1.7.5.13.

Temps are fine (around 64 celsius). Have no idea whats happening. Other cards are unaffected.

**Comment by S74nk0** [comment]
@DrRobotto send the zipped logs folder to stanko@nicehash.com

**Comment by S74nk0** [comment]
@DrRobotto This issue happens when switching to **NeoScrypt (ccminer)** and back. To mitigate this issue disable **NeoScrypt (ccminer)**. We will include **NeoScrypt** in **excavator** and fix this issue. But for now the quick fix solution would be to disable **NeoScrypt (ccminer)**.

**Comment by DrRobotto** [comment]
Thank you very much, this solved the problem
