### ISSUE TITLE
Nicehashminer2 is closing other applications.

### ISSUE THREAD

**Issue by Squall-Leonhart** [nicehash/NiceHashMiner2#78]
Since installing this new version, my computer has at times closed applications when i have not been present

This is occuring on a wide range of applications, and there is no history of a memory pressure event in event viewer.

Applications affected have no real correlation to each other.

It closes 
Total commander
Windows media player
Utorrent
Internet Explorer (and does not save tabs)
Skype
Poolmon
Process Explorer
UPS monitoring software
Network indicator
Outlook.exe
notepad.exe
it even tried to close MirC but was blocked by the exit confirmation

when i left my computer there was 16GB free, so i do not believe windows closed these by itself,
and there is no errors logged for any of these applications. (would not explain the mirc window either.

This MAY be a result of third party miners doing dodgy things.

**Comment by jaretburkett** [comment]
Could you upload log files for when this happens? Also, would you mind trying  starting/stopping/starting... the miners to see if this replicates the problem?

**Comment by Squall-Leonhart** [comment]
more likely to reproduce a driver stop than this just spamming the start/stop buttons....

i've never seen it happen while im at the machine, only when i'm away from it and the machine is locked, i come back and these applications are no longer open, or like mircs case, the exit confirmation window is up.

next time it happens i'll grab logs, but i didn't see anything in them that correlates, and i've turned off 3rd party miners for the moment.

**Comment by Squall-Leonhart** [comment]
Ok, i believe it just occurred while i was present at my computer.

when it occurred, the excavator server was restarted.

when it did the following apps were closed.
MSE's tray icon
Outlook
Process Explorer
and XFI mode switcher

who do i send logs to?

**Comment by AngryOverlord** [comment]
This also has been happening to me the past few days as well. I saw it once and it also happened when excavator server restarted. I have forwarded the most recent logs to stanko@nicehash.com

**Comment by Squall-Leonhart** [comment]
Thank goodness, I was beginning to think it was just me.

**Comment by Phuzzyhead** [comment]
This also closed MS Edge and Maxthon Browsers for me.

**Comment by Hueristic** [comment]
You probably have a trojan. what ports are open? :D

try wireshark.

**Comment by Squall-Leonhart** [comment]
There is no trojan, the issue only occurs with Nicehashminer 2.0
Never without it running, and never with 1.0.

PS.
What is NQ?

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
