### ISSUE TITLE
Nicehash Miner 2.0 not optimizing highest hash rate

### ISSUE THREAD

**Issue by sil2222** [nicehash/NiceHashMiner2#8]
When mining on v2.0 miner is hashing only 10.00 usd per day when I run miner version 1.7.5.12 miner automatically finds highest hash payout for me at 13.00 usd per day. Version 2.0 is not finding best optimized rate for my miner and assigning me to lower payout rate. Also its harder to turn off miners I may not want to use like my CPU old version a  lot more user friendly to be able to turn off cpu mining.

**Comment by S74nk0** [comment]
@sil2222 please post the logs folder (zipped) here or send it to stanko@nicehash.com.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.6 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.6 Alpha**
