### ISSUE TITLE
Virtual CPUs on NHM2

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner2#9]
So I tried out NHM2 on VM on a server.
The VM has 4 cores, which are detected in system as 4 sockets and 4 virtual processors.
Previous version of NHM was detecting this as one CPU with 4 cores, which made sense.
NHM2 detects as 4 separate CPUs and launches 4 separate xmr-stak-cpu miners for each CPU, but with same worker name.

I can't say anything about performance, it seems approx the same.
But it's not very nice visually.
**UPDATE** it doesn't have any effect on speed on the VM itself, but on the website (obviously) such small hashrate (45 h/s) is not detected properly and shows either 0.1 kH/s or 0 (most often 0)

**Comment by S74nk0** [comment]
@giosal NHM2 CPU detection might not work correctly under a Virtual Machine (most probably it will not work correctly). If this issue wasn't present in NHM1 under a VM we will make sure to update the new detection code to take VMs into account.

**Comment by giosal** [comment]
@S74nk0 sorry for late answer, yes, it was not present in NHM1, and as of v. 2.0.0.7 it's still present in NHM2.
xmr-stak-cpu launched separately detects vCPUs correctly

**Comment by S74nk0** [comment]
@giosal Please try the following (this **patch** should work under a **VM**):
 - Download this [patch](https://github.com/nicehash/NiceHashMiner2/releases/download/bins/NewCPUDetection.zip)
 - extract **NewCPUDetection.zip** and run **update_and_log.bat**
 - run nhm2 after that (CPU should hopefully be detected)
 - report back and post the **update_and_log.bat** here

**Comment by S74nk0** [comment]
@giosal maybe check [this](https://github.com/nicehash/NiceHashMiner2/issues/95) it is related

**Comment by mflavius** [comment]
What about virtual GPU's? My server has a virtual GPU thats not being detected by NHM2

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
