### ISSUE TITLE
NiceHash Miner 2.0.0.7 Alpha unable to detect Xeon CPU

### ISSUE THREAD

**Issue by gsoft** [nicehash/NiceHashMiner2#95]

**Comment by S74nk0** [comment]
@gsoft What Xeon CPU exactly? Please be specific on the model.

**Comment by gsoft** [comment]
1.7 has detect they as Intel Xeon E5-2630v3 2.4Ghz

**Comment by S74nk0** [comment]
@gsoft Is the system under a VM or bare metal?

**Comment by gsoft** [comment]
rack mount server
https://www.hpe.com/us/en/product-catalog/servers/proliant-servers/pip.specifications.hpe-proliant-dl360-gen9-server.7252836.html

**Comment by S74nk0** [comment]
@gsoft Please try the following:
 - Download this [patch](https://github.com/nicehash/NiceHashMiner2/releases/download/bins/NewCPUDetection.zip)
 - extract **NewCPUDetection.zip** and run **update_and_log.bat**
 - run nhm2 after that (CPU should hopefully be detected)
 - report back and post the **debug_all_out.txt** here

**Comment by gsoft** [comment]
Hi! 
U forget a depence - msvcp120.dll - fixed..
And I've got error 0xc000007b

**Comment by S74nk0** [comment]
@gsoft sorry about that. I have updated the download link with the missing dependencies. Can you please try again?

**Comment by gsoft** [comment]
Still catch 0xc000007b.

**Comment by S74nk0** [comment]
@gsoft If you install [VS2013 	vcredist_x86.exe](https://www.microsoft.com/en-us/download/details.aspx?id=40784) it would be safer. Maybe the included dlls are x64

**Comment by S74nk0** [comment]
@gsoft is there any **debug_all_out.txt** file in the extracted path?

**Comment by gsoft** [comment]
Already have 2012 x64 and 2015 x64

**Comment by gsoft** [comment]
out is empty

**Comment by gsoft** [comment]
![msvc](https://user-images.githubusercontent.com/944460/27350034-3bfdbf4a-560a-11e7-8f26-4a7f789ec9f2.PNG)

**Comment by S74nk0** [comment]
@gsoft We need C++ 2013 x86 **the 32bit version** for this. These two will not work

**Comment by gsoft** [comment]
2013 does not help
![msvs2013](https://user-images.githubusercontent.com/944460/27350281-fa39a6ae-560a-11e7-9b49-0ea9e6db92c0.PNG)

**Comment by gsoft** [comment]
![cpud_fail](https://user-images.githubusercontent.com/944460/27350343-23407a46-560b-11e7-922b-a19356004afd.PNG)

**Comment by S74nk0** [comment]
@gsoft Still not right version **vcredist_x86.exe** is the install file. 
![vcredist](https://user-images.githubusercontent.com/1517233/27350469-b5e004b8-55fa-11e7-8ddd-c1b096d94ee6.PNG)

**Comment by gsoft** [comment]
One sec

**Comment by gsoft** [comment]
Its work! Both make same log

> {
> 	"Brand" : "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz",
> 	"PhysicalCores" : 8,
> 	"LogicalCores" : 16,
> 	"TotalCores" : -1,
> 	"PhysicalCPUsCount" : 2,
> 	"Features" : {
> 		"AVX2" : true,
> 		"AVX" : true,
> 		"AES" : true,
> 		"SSE42" : true,
> 		"SSE41" : true,
> 		"SSE2" : true
> 	}
> }

**Comment by gsoft** [comment]
NHM has detect Xeon CPU

**Comment by S74nk0** [comment]
@gsoft this is good news. Does nhm2 see the **CPUs**? This is a dual CPU setup?

**Comment by gsoft** [comment]
Yep!

**Comment by S74nk0** [comment]
@gsoft On the side note I would advise to use NHMv1 for CPU exclusive mining until v2.0.0.8 as dual CPU mining most likely will not yield best performance in NHMv2.0.0.7. 
Thanks for your feedback and patience.

**Comment by gsoft** [comment]
Another case, on other desktop node, we have old NVidia GPU 450 - and NHM@ they fail detect too ;)
Open an new issue?

**Comment by gsoft** [comment]
In fact, I'm more interested in multi-CPU optimization because we were given a server rack with 2 and 4 processors 8)

**Comment by S74nk0** [comment]
Those GPUs seem to be less than SM3.0 ([source](https://en.wikipedia.org/wiki/CUDA)). We will drop support for lower compute versions.
For CPU mining use NHMv1 until we release the NHMv2 stable release.
NHMv1 has the correct CPU affinity settings. And the CPU miners are exactly the same

**Comment by S74nk0** [comment]
NHMv1 will detect the best setup on a clean benchmark. Make sure to run it on a clean OS start for best accuracy.

**Comment by gsoft** [comment]
For info: I run 2.0.0.6 again - it found Xeon CPU - but only one.

**Comment by gsoft** [comment]
Still breaking up - Mining details is empty :|

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**

**Comment by Dannylee12307** [comment]
Hi Sir,
Can I know the VM can use the Nice Hash Miner?

**Comment by Avrhy77** [comment]
Yess

2017-10-25 22:17 GMT+07:00 Dannylee12307 <notifications@github.com>:
