### ISSUE TITLE
Starting Excavator Server

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner2#97]
Hi , when i start nhm2007 it takes 10 years , it still says Starting the server, what the heck is it doing

**Comment by S74nk0** [comment]
@imrecsoka open the task manager and find excavator process and kill it. NHM2 will get passed it. This is just a workaround until we make a new release.

**Comment by S74nk0** [comment]
@imrecsoka excavator has been updated. Please restart **nhm2007** **it will update excavator** and report if it finishes loading.

**Comment by S74nk0** [comment]
@imrecsoka  we have released a new [excavator_v1.2.9a](https://github.com/nicehash/excavator/releases/tag/v1.2.9a) and it should have this issue fixed. After NiceHash Miner 2.0.0.7 restart it will update excavator to **v1.2.9a**.
Please report if **NiceHash Miner 2.0.0.7** and **excavator v1.2.9a** resolve this issue.

**Comment by imrecsoka** [comment]
Hi,
I will re-install nhm2007
run the benchmarks for ALL algos against all devices.
See how it goes.
Currently for me,  Claymore and FierceUK Stak CPU are the best tools, which nicehashminer or multipoolminer use.
I am curious to see how or what Excavator does, as it seems to be new in the hood to me?
Greetings from South Africa and cheers, I hope to be able to donate to this project as well.

**Comment by S74nk0** [comment]
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**
